### ISSUE TITLE
[PlayerMB] Generowanie listy m3u

### ISSUE THREAD

**Issue by DeGH** [kodi-pl/kodipl#6]
Być może warto rozważyć dodanie możliwości generowania list m3u z kanałami TV.

Obrazek poglądowy:
!['obraz'](https://i.imgur.com/z7nwdeu.png)

Przykładowa struktura pliku:
```
#EXTM3U
#EXTINF:-1 tvg-id="xxx" tvg-name="Nazwa Kanału" tvg-logo="LinkDoLogo.png" group-title="JakasTam",Nazwa Kanału
plugin://plugin.video.playermb/play?xxxx
```

**Comment by mm1992** [comment]
Hej,
myślałem o tym.
Najprawdopodobniej byłbym w stanie coś takiego zrobić.
Bazowałbym na analogicznej funkcjonalności wtyczki do portalu WP Pilot.
